version: '3.8'
services:
  voyage-two:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: santos
    restart: always
    networks:
      - api_santos_network
    ports:
      - "3000:3000"


networks:
  api_santos_network:
    name: api_santos_network
    driver: bridge

