version: '3.8'
services:
  voyage-two:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: santos
    restart: always
      # deploy:
      # resources:
      #limits:
      #cpus: '0.3'
    #memory: 128M
    networks:
      - api_santos_network
    ports:
      - "3000:3000"


networks:
  api_santos_network:
    name: api_santos_network
    driver: bridge

